In [1]:
import numpy as np

In [43]:
import torch
from torch.utils.data import Dataset, DataLoader, ConcatDataset, ChainDataset

In [30]:
class D1(Dataset):
    def __init__(self, **kw):
        self.indices = range(1, 21)
    
    def __getitem__(self, ix):
            return self.indices[ix]
        
    def __len__(self):
        return len(self.indices)

In [31]:
class D2(Dataset):
    def __init__(self, **kw):
        self.indices = range(21, 41)
    
    def __getitem__(self, ix):
            return self.indices[ix]
        
    def __len__(self):
        return len(self.indices)

In [32]:
class D3(Dataset):
    def __init__(self, **kw):
        self.indices = range(41, 61)
    
    def __getitem__(self, ix):
            return self.indices[ix]
        
    def __len__(self):
        return len(self.indices)

In [51]:
d1 = D1()
d2 = D2()
d3 = D3()
cd = ConcatDataset([d1, d2, d3])

In [52]:
loader = DataLoader(dataset=cd, batch_size=8, shuffle=True)

In [53]:
for batch in loader:
    print(batch)

tensor([49, 40, 23, 26, 16, 22, 45, 48])
tensor([28, 41, 47,  6, 18, 37, 51,  7])
tensor([58, 31, 11, 50, 14,  2, 34, 55])
tensor([59, 17, 19,  8, 39, 13, 15, 38])
tensor([57, 10, 44,  1, 35,  5, 54, 42])
tensor([30, 12, 32, 43,  4, 56, 21, 60])
tensor([29, 27, 24, 25, 20, 46, 53, 36])
tensor([52,  9, 33,  3])
